### ISSUE TITLE
Can't add or remove items from the scope list (left)

### ISSUE THREAD

**Issue by albertbori** [aziz/tmTheme-Editor#113]
Attempted to add:
Name: Operator
Scope: keyword.operator

Result: no change

Attempted to remove:
Name: Keyword
Scope: Keyword

Result: no change

**Comment by alexhoward3** [comment]
I'm having this same issue, but switching the views does not resolve it. However, if I open the color adjustments window and hit "reset" the new scope appears.

Also, new scopes do not get removed when clicking the minus button, nor do they get removed after clicking "reset" in the color adjustment window.

**Comment by aziz** [comment]
Hi guys, sorry I'm busy this week, but I'll look into this nasty bug and fix it ASAP. Thanks for reporting.

**Comment by bathos** [comment]
Confirming the same behavior on Chrome 41 and Firefox on Linux. The Color Adjustments -> Reset button is the only thing that causes the scope list to update (although unlike what alexhoward3 experienced, deleted items do disappear when I do this).

It's obviously an amazing tool though despite being pretty tough to use at the moment -- glad I found it, bookmarked for a later date :)

**Comment by aziz** [comment]
fixed in 0.8.1
