### ISSUE TITLE
RE : resetting color box

### ISSUE THREAD

**Issue by nerzadler** [aziz/tmTheme-Editor#150]
![capture d ecran 2015-05-24 a 18 33 51](https://cloud.githubusercontent.com/assets/12514349/7789499/ca9fd54c-0262-11e5-9404-64e1b53ef72f.png)

Hi again, as requested, here is a screen-shot from my computer.
Loic

**Comment by aziz** [comment]
Oh, I guess I found the source of miss understanding! You need to double click on the row to open the popover dialog box. inside that dialog box there're two color-boxes that has reset buttons. in addition you can manually edit the color values inside two textboxes.

**Comment by nerzadler** [comment]
Oh, right. Sorry, I feel dumb now.

Thanx for your help !
