### ISSUE TITLE
Question: Usage of cookies

### ISSUE THREAD

**Issue by igncp** [aziz/tmTheme-Editor#158]
Hi there,

I am looking the source code of this great web app and I noticed that you use cookies management with cookieParser in the backend and $.cookie in the frontend. You store some data in cookies like the `preview_lang` or the `gallery_visible` variables. However, these cookies data is not used in the backend side.

On the other hand, you also use the LocalStorage API to cache some of the view data in the browser. My question is: why not use the localStorage for the previous variables too? Is there any underlying reason, just to differentiate concepts? If there isn't any reason, would you consider a PR to change this to use only LocalStorage?

Thanks

**Comment by aziz** [comment]
Short answer is: it's on my todo list, with a low priority.
```
☐ get rid of cookies, use localstorage
```

Long Answer:
Here's a  story how I ended up here. This started as a small app for me to solve my own problem editing my theme and also learn Angular and new HTML5 technologies. 
The early versions were using FileSystem API to store theme files with no cookies. then I needed to persist the state of the app and I tries to use ng-cookies but it was pretty useless at the time (they fixed it recently in 1.4) so I used $.cookie.
Then I got tired of Async and Slowness of FileSystem API and disappointed in its slow adoption by other browser vendors so I moved to localstorage. 
LocalStorage is sync in nature but has limited storage quota, which is another problem I've not completely fixed here. 
It's a work in progress and I appreciate any PR
