### ISSUE TITLE
Customized theme not working

### ISSUE THREAD

**Issue by serneelsalexis** [aziz/tmTheme-Editor#162]
Hi,

I click on "customize theme", copy my PHP file, hit "Save" and nothing changes.
Tried on FF, Chrome, Safari,

Cheers,

**Comment by LOQUILLO** [comment]
Hi @aziz "Customize Preview Code" isn't working, code pasted don't save.

**Comment by aziz** [comment]
You're right, I'll fix it ASAP.

**Comment by LOQUILLO** [comment]
Hi @aziz, "Customize Preview Code" is working.
Thanks for ths fix.
