### ISSUE TITLE
Theme editing not working

### ISSUE THREAD

**Issue by tushortz** [aziz/tmTheme-Editor#175]
I was just wondering. Is something wrong with the way I added my theme. It shows on theherokuapp website among the lists but i can't see any preview codes or color highlighting as well as any scopes

**Comment by aziz** [comment]
More information please! what's the name of you theme, how can we recreate this issue?

**Comment by tushortz** [comment]
It's called Wildlife and there are two versions. Wildlife - Day and
Wildlife - Night. I realised that Wildlife - Day was working yesterday but
the Wildlife - Night doesn't do syntax highlighting.

To view it, you go on the theme-editor website and view the themes at the
bottom. Click Wildlife - Night. The link changes but the syntax
highlighting remains unchanged

**Comment by aziz** [comment]
Thanks for the info. I'll look into it.

**Comment by tushortz** [comment]
Yeah no worries. Thanks
