### ISSUE TITLE
Failed to instantiate module ThemeEditor

### ISSUE THREAD

**Issue by jShi-git** [aziz/tmTheme-Editor#177]
![stackedmap](https://cloud.githubusercontent.com/assets/3771576/10420986/d769a3f6-70d1-11e5-8aa7-6444cfb3c238.jpg)

**Comment by aziz** [comment]
`ui.bootstrap.stackedMap` is not something I'm using. are you sure it's not one of your browser extensions that's breaking the page. it's working for me just fine.  

Please provide more information on how to recreate the error if you still have this issue. 
Feel free to reopen it.

**Comment by jShi-git** [comment]
I checked out the project again in a new path and try out some other browses, but still has the same problem.

**ENV:**
```
node v4.1.2
npm 2.14.4
```

**INSTALL && RUN:**
```
git clone https://github.com/aziz/tmTheme-Editor.git
cd tmTheme-Editor
npm install
gulp
coffee app/back/app.coffee
```
