### ISSUE TITLE
Drop native color picker in favor of JS implementation.

### ISSUE THREAD

**Issue by stil** [aziz/tmTheme-Editor#19]
I think, that tmTheme editor is now unusable, because of terrible Windows color picker.
Look at the screenshot: http://i.imgur.com/g7378kZ.png

I'd like to convert one of the Notepad++ themes, but I can't enter hex color value using that.
There are many JavaScript color picker plugins you could implement in the editor.

**Comment by aziz** [comment]
Fixed in 0.10.0 by implementing an internal color picker
