### ISSUE TITLE
Can't install theme.

### ISSUE THREAD

**Issue by xSynthx** [aziz/tmTheme-Editor#238]
So, I found the anarchist theme on the website, how would I use it with sublime text 3 using the downloaded file because what im trying apparently isnt going to work:

Sublime preferences:
```
"color_scheme": "Themes/Anarchist.tmTheme",
```
and this is all I get: 
![Image Link](https://image.prntscr.com/image/ItVnJ8e7SoCsu3sW8AWX1A.png "Image")
The file is there, and everything.

**Comment by xSynthx** [comment]
Anyone that can help?

**Comment by aziz** [comment]
You save the file. put it in your Sublime User folder (you can also create a separate sub folder for it) and then in the settings file you address it from the Packages directory like this:

```
"color_scheme": "Packages/User/Anarchist.tmTheme",
```

If you don't know where is the Sublime User folder just google it.

**Comment by xSynthx** [comment]
That worked, thank you very much!

For those of you that do not know the location of the users folder, it is here:

```
For Sublime 2, the locations are the following:
     Windows: %APPDATA%\Sublime Text 2
     OS X: ~/Library/Application Support/Sublime Text 2
     Linux: ~/.config/sublime-text-2

This information is available here: http://docs.sublimetext.info/en/sublime-text-2/basic_concepts.html#the-data-directory

For Sublime 3, the locations are the following:

    Windows: %APPDATA%\Sublime Text 3
    OS X: ~/Library/Application Support/Sublime Text 3
    Linux: ~/.config/sublime-text-3

This information is available here:http://docs.sublimetext.info/en/sublime-text-3/basic_concepts.html#the-data-directory
```
