### ISSUE TITLE
app not working?

### ISSUE THREAD

**Issue by pgomba** [aziz/tmTheme-Editor#275]
Just noticed the app is no longer working on https://tmtheme-editor.herokuapp.com/

**Comment by 26F** [comment]
Not working in chrome or firefox. With this message:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by nishanmudalige** [comment]
I get the same error when I tried accessing the site with the edge browser on windows and Safari on macOS.

**Comment by Jael-Esther** [comment]
I've also been having this issue on Firefox and Chrome (Windows 10).
![image](https://user-images.githubusercontent.com/120145278/206828405-d4f4ee2c-81eb-4836-a6e0-5590444f7bc1.png)

**Comment by jimmybrancaccio** [comment]
Of note this has nothing to do with your web browser. The app is "broken" on Heroku. I wouldn't be surprised if it was removed since Heroku no longer offers free plans.

EDIT: Also I've noticed how old the versions of Node.js and `npm` this app is using so I also wouldn't be surprised if Heroku no longer supported those versions 😝

**Comment by GazerGirl49** [comment]
Same.

**Comment by Sjb4243** [comment]
Yep, down for me too. Tried seeing if I could run it locally but no luck there either.

**Comment by niraj8** [comment]
You could try running locally on the branch in this PR -> https://github.com/aziz/tmTheme-Editor/pull/277
Use node 14.x

**Comment by forivall** [comment]
I have the above branch running at https://tmtheme-editor.glitch.me

**Comment by ansoncall** [comment]
Sadly it looks like Glitch web hosting is gone as well. 
[https://blog.glitch.com/post/changes-are-coming-to-glitch/ ](https://blog.glitch.com/post/changes-are-coming-to-glitch/ )

**Comment by forivall** [comment]
bogus. I forgot what changes i made to get it working on glitch - i can diff the archive of my glitch version vs niraj's branch to see what i did, and move it to one of the [alternatives suggested by jennschiffer](https://livelaugh.blog/posts/glitch-alternatives/), probably [val.town](https://www.val.town/) or render.com, or [digitalocean dokku](https://marketplace.digitalocean.com/apps/dokku)

**Comment by jimmybrancaccio** [comment]
I tossed up a copy here - https://tmtheme-editor.linuxbox.ninja. This uses some changes from #277.
