### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by FichteFoll** [aziz/tmTheme-Editor#85]
Sorry for not creating an issue for each thing, but since you are keeping a local todo list anyway I guess it won't hurt too much. Also sorry if these have been mentioned already.

So yeah, I was testing the awesome 0.4 update and noticed these things:

- Unable to set background (or foreground) alpha.
- On-Hover highlight for the gallery items and scope entries would be nice - only visual though.
- When a color scheme defines more than two scopes that some text matches it is hard to find the most inner one because it seems it only uses 2 colors for underline. Example: line 46 in Python language.
- When you invert http://tmtheme-editor.herokuapp.com/#/Zenburn twice (example) a lot of colors are now plain black
- You show the scope at the bottom in "inner to outer" order, which is confusing because they are used the other way around everywhere else.

**Comment by aziz** [comment]
> Unable to set background (or foreground) alpha.

Fixed

**Comment by FichteFoll** [comment]
>On-Hover highlight for the gallery items and scope entries would be nice - only visual though.

is still open though.

Also, did the hover-highlight scope visualization disappear?

**Comment by aziz** [comment]
> Also, did the hover-highlight scope visualization disappear?
Added a new feature called ScopeHunter which is inspired by @facelessuser's  ScopeHunter plugin. I believe it's better than what we had before. the old functionality is still there though. to get it you need to turn on ScopeHunter. click on an element in preview mode to freeze up the scope hunting then click on name or scope on the `Matching Rule` section. this will highlight the matching rule in sidebar. 

> On-Hover highlight for the gallery items and scope entries would be nice - only visual though.

Added this and played with it for a while but didn't like the visual pollution it adds. 

Closing this issue.
