### ISSUE TITLE
adding general colors with alpha channel

### ISSUE THREAD

**Issue by q6** [aziz/tmTheme-Editor#87]
I really think that this online editor is going somewhere, it very easy and pleasent to use. Here are two things I wish were better:
 - Clear color: right now once cannot remove a color such as the background color, please allow the user to remove colors and replace them with an all aplha background
 - custom code: right now the code examples are too short and do not contain all the language definitions in them. Please allow the user to paste their own code

**Comment by aziz** [comment]
Fixed in 0.10.0 by implementing an internal color picker
